-d /home/quang1806/Desktop/Gowin/CH9_UART_LOOP/impl/gwsynthesis/uart_loopback.vg
-p GW5A-25A-UBGA324-1
-pn GW5A-LV25UG324ES
-cst /home/quang1806/Desktop/Gowin/CH9_UART_LOOP/src/uart_loopback.cst
-cfg /home/quang1806/Desktop/Gowin/CH9_UART_LOOP/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
